# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Python (pip)
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt
    schedule:
      interval: "daily" # How often to check for updates (daily, weekly, monthly)
    target-branch: "main" # Or your default branch
    # You can add labels, reviewers, assignees, etc.
    # labels:
    #  - "python"
    #  - "dependencies"
    # reviewers:
    #  - "your-username"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/" # Location of Dockerfile
    schedule:
      interval: "daily"
    target-branch: "main"
    # labels:
    #  - "docker"
    #  - "dependencies"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your .github/workflows directory
    schedule:
      interval: "daily"
    target-branch: "main"
    # labels:
    #  - "github_actions"
    #  - "dependencies"
